---
# vars specific to any centos 8.x version

common_yum_repos:
  lab-extras:
    name: "lab-extras"
    baseurl: "http://{{ mirror_host }}/lab-extras/8/"
    enabled: 1
    gpgcheck: 0

# These will overwrite the repo files that come with a CentOS installation
yum_repos:
  CentOS-AppStream:
    name: "CentOS-$releasever - AppStream"
    mirrorlist: file:///etc/yum.repos.d/CentOS-AppStream-mirrorlist
    gpgcheck: 1
    enabled: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
  CentOS-Base:
    name: "CentOS-$releasever - Base"
    mirrorlist: file:///etc/yum.repos.d/CentOS-Base-mirrorlist
    gpgcheck: 1
    enabled: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
  CentOS-Extras:
    name: "CentOS-$releasever - Extras"
    mirrorlist: file:///etc/yum.repos.d/CentOS-Extras-mirrorlist
    gpgcheck: 1
    enabled: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial

# These are files in roles/testnodes/templates/mirrorlists/8/
yum_mirrorlists:
  - CentOS-AppStream-mirrorlist
  - CentOS-Base-mirrorlist
  - CentOS-Extras-mirrorlist

packages:
  # for package-cleanup
  - dnf-utils
  - sysstat
  - libedit
  - boost-thread
  - xfsprogs
  - gdisk
  - parted
  - libgcrypt
  - fuse-libs
  - openssl
  - libuuid
  - podman
  # for cephadmunit.py to uniformly run 'docker kill -p ...'
  - podman-docker
  - attr
  - ant
  - lsof
  - gettext
  - bc
  - xfsdump
  - blktrace
  - usbredir
  - libev-devel
  - valgrind
  - nfs-utils
  # for xfstests
  - ncurses-devel
  # for s3 tests
  # for workunits,
  - gcc
  - git
  # qa/workunits/rados/test_python.sh
  - python3-nose
  # for cram tests
  - python3-virtualenv
  # for rbd qemu tests
  - genisoimage
  - qemu-img
  - qemu-kvm-core
  - qemu-kvm-block-rbd
  # for pjd tests
  - libacl-devel
  # for fs tests,
  - dbench
  - autoconf
  # for test-crash.sh
  - gdb
  - iozone
  - lvm2

epel_packages: []

nfs_service: nfs-server

ntp_service_name: chronyd
